// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: conf.proto

package conf

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Config_ResolveMode int32

const (
	Config_Random     Config_ResolveMode = 0
	Config_InOrder    Config_ResolveMode = 1
	Config_Concurrent Config_ResolveMode = 2
)

var Config_ResolveMode_name = map[int32]string{
	0: "Random",
	1: "InOrder",
	2: "Concurrent",
}

var Config_ResolveMode_value = map[string]int32{
	"Random":     0,
	"InOrder":    1,
	"Concurrent": 2,
}

func (x Config_ResolveMode) String() string {
	return proto.EnumName(Config_ResolveMode_name, int32(x))
}

func (Config_ResolveMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b6ecbfc68e85c65, []int{0, 0}
}

type Server_Type int32

const (
	Server_UDP Server_Type = 0
	Server_DOH Server_Type = 1
)

var Server_Type_name = map[int32]string{
	0: "UDP",
	1: "DOH",
}

var Server_Type_value = map[string]int32{
	"UDP": 0,
	"DOH": 1,
}

func (x Server_Type) String() string {
	return proto.EnumName(Server_Type_name, int32(x))
}

func (Server_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b6ecbfc68e85c65, []int{1, 0}
}

type Config struct {
	Servers              []Server           `protobuf:"bytes,1,rep,name=server,proto3" json:"server"`
	ResolveMode          Config_ResolveMode `protobuf:"varint,2,opt,name=resolve_mode,json=resolveMode,proto3,enum=conf.Config_ResolveMode" json:"resolve_mode,omitempty"`
	ListenAddr           string             `protobuf:"bytes,3,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	LogQueries           bool               `protobuf:"varint,4,opt,name=log_queries,json=logQueries,proto3" json:"log_queries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b6ecbfc68e85c65, []int{0}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Config.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return m.Size()
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetServers() []Server {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *Config) GetResolveMode() Config_ResolveMode {
	if m != nil {
		return m.ResolveMode
	}
	return Config_Random
}

func (m *Config) GetListenAddr() string {
	if m != nil {
		return m.ListenAddr
	}
	return ""
}

func (m *Config) GetLogQueries() bool {
	if m != nil {
		return m.LogQueries
	}
	return false
}

type Server struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 Server_Type `protobuf:"varint,2,opt,name=type,proto3,enum=conf.Server_Type" json:"type,omitempty"`
	HostPort             string      `protobuf:"bytes,3,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	DohUrl               string      `protobuf:"bytes,4,opt,name=doh_url,json=dohUrl,proto3" json:"doh_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b6ecbfc68e85c65, []int{1}
}
func (m *Server) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Server.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(m, src)
}
func (m *Server) XXX_Size() int {
	return m.Size()
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Server) GetType() Server_Type {
	if m != nil {
		return m.Type
	}
	return Server_UDP
}

func (m *Server) GetHostPort() string {
	if m != nil {
		return m.HostPort
	}
	return ""
}

func (m *Server) GetDohUrl() string {
	if m != nil {
		return m.DohUrl
	}
	return ""
}

func init() {
	proto.RegisterEnum("conf.Config_ResolveMode", Config_ResolveMode_name, Config_ResolveMode_value)
	proto.RegisterEnum("conf.Server_Type", Server_Type_name, Server_Type_value)
	proto.RegisterType((*Config)(nil), "conf.Config")
	proto.RegisterType((*Server)(nil), "conf.Server")
}

func init() { proto.RegisterFile("conf.proto", fileDescriptor_0b6ecbfc68e85c65) }

var fileDescriptor_0b6ecbfc68e85c65 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xc1, 0x0e, 0xd2, 0x40,
	0x10, 0x86, 0x59, 0x68, 0x5a, 0x98, 0x12, 0xac, 0x1b, 0x13, 0x1b, 0x4d, 0xa0, 0x69, 0x62, 0xd2,
	0x53, 0x4d, 0x30, 0x7a, 0xf1, 0x24, 0x70, 0xd0, 0x83, 0x01, 0x57, 0x39, 0x37, 0xc8, 0x2e, 0x85,
	0xa4, 0xec, 0xd4, 0x69, 0x21, 0xe1, 0x39, 0x7c, 0x29, 0x8e, 0x3e, 0x01, 0x31, 0x7d, 0x08, 0xcf,
	0xa6, 0xbb, 0x18, 0xb9, 0xfd, 0xf3, 0xcd, 0xbf, 0xff, 0xce, 0xec, 0x02, 0x6c, 0x51, 0xef, 0xd2,
	0x92, 0xb0, 0x46, 0xee, 0xb4, 0xfa, 0xc5, 0xb3, 0x1c, 0x73, 0x34, 0xe0, 0x75, 0xab, 0x6c, 0x2f,
	0xfe, 0xc3, 0xc0, 0x9d, 0xa3, 0xde, 0x1d, 0x72, 0xfe, 0x16, 0xdc, 0x4a, 0xd1, 0x59, 0x51, 0xc8,
	0xa2, 0x5e, 0xe2, 0x4f, 0x87, 0xa9, 0xc9, 0xf8, 0x6a, 0xd8, 0xec, 0xc9, 0xf5, 0x36, 0xe9, 0x34,
	0xb7, 0x89, 0x67, 0xeb, 0x4a, 0xdc, 0xcd, 0xfc, 0x3d, 0x0c, 0x49, 0x55, 0x58, 0x9c, 0x55, 0x76,
	0x44, 0xa9, 0xc2, 0x6e, 0xc4, 0x92, 0xd1, 0x34, 0xb4, 0x87, 0x6d, 0x74, 0x2a, 0xac, 0xe1, 0x33,
	0x4a, 0x25, 0x7c, 0xfa, 0x5f, 0xf0, 0x09, 0xf8, 0xc5, 0xa1, 0xaa, 0x95, 0xce, 0x36, 0x52, 0x52,
	0xd8, 0x8b, 0x58, 0x32, 0x10, 0x60, 0xd1, 0x07, 0x29, 0xc9, 0x18, 0x30, 0xcf, 0x7e, 0x9c, 0x14,
	0x1d, 0x54, 0x15, 0x3a, 0x11, 0x4b, 0xfa, 0x02, 0x0a, 0xcc, 0xbf, 0x58, 0x12, 0xbf, 0x03, 0xff,
	0x21, 0x9d, 0x03, 0xb8, 0x62, 0xa3, 0x25, 0x1e, 0x83, 0x0e, 0xf7, 0xc1, 0xfb, 0xa4, 0x97, 0x24,
	0x15, 0x05, 0x8c, 0x8f, 0x00, 0xe6, 0xa8, 0xb7, 0x27, 0x22, 0xa5, 0xeb, 0xa0, 0x1b, 0xff, 0x64,
	0xe0, 0xda, 0x55, 0x38, 0x07, 0x47, 0x6f, 0x8e, 0x2a, 0x64, 0xe6, 0x76, 0xa3, 0xf9, 0x2b, 0x70,
	0xea, 0x4b, 0xf9, 0x6f, 0x9b, 0xa7, 0x8f, 0x4f, 0x91, 0x7e, 0xbb, 0x94, 0x4a, 0x98, 0x36, 0x7f,
	0x09, 0x83, 0x3d, 0x56, 0x75, 0x56, 0x22, 0xd5, 0xf7, 0xe9, 0xfb, 0x2d, 0x58, 0x21, 0xd5, 0xfc,
	0x39, 0x78, 0x12, 0xf7, 0xd9, 0x89, 0x0a, 0x33, 0xf7, 0x40, 0xb8, 0x12, 0xf7, 0x6b, 0x2a, 0xe2,
	0x10, 0x9c, 0x36, 0x83, 0x7b, 0xd0, 0x5b, 0x2f, 0x56, 0x41, 0xa7, 0x15, 0x8b, 0xe5, 0xc7, 0x80,
	0xcd, 0x86, 0xd7, 0x66, 0xcc, 0x7e, 0x35, 0x63, 0xf6, 0xbb, 0x19, 0xb3, 0xef, 0xae, 0xf9, 0xa3,
	0x37, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x95, 0xe3, 0x18, 0xcd, 0x01, 0x00, 0x00,
}

func (m *Config) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Config) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Config) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.LogQueries {
		i--
		if m.LogQueries {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.ListenAddr) > 0 {
		i -= len(m.ListenAddr)
		copy(dAtA[i:], m.ListenAddr)
		i = encodeVarintConf(dAtA, i, uint64(len(m.ListenAddr)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ResolveMode != 0 {
		i = encodeVarintConf(dAtA, i, uint64(m.ResolveMode))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Servers) > 0 {
		for iNdEx := len(m.Servers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Servers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintConf(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Server) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Server) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Server) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.DohUrl) > 0 {
		i -= len(m.DohUrl)
		copy(dAtA[i:], m.DohUrl)
		i = encodeVarintConf(dAtA, i, uint64(len(m.DohUrl)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.HostPort) > 0 {
		i -= len(m.HostPort)
		copy(dAtA[i:], m.HostPort)
		i = encodeVarintConf(dAtA, i, uint64(len(m.HostPort)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Type != 0 {
		i = encodeVarintConf(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintConf(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintConf(dAtA []byte, offset int, v uint64) int {
	offset -= sovConf(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Config) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Servers) > 0 {
		for _, e := range m.Servers {
			l = e.Size()
			n += 1 + l + sovConf(uint64(l))
		}
	}
	if m.ResolveMode != 0 {
		n += 1 + sovConf(uint64(m.ResolveMode))
	}
	l = len(m.ListenAddr)
	if l > 0 {
		n += 1 + l + sovConf(uint64(l))
	}
	if m.LogQueries {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Server) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovConf(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovConf(uint64(m.Type))
	}
	l = len(m.HostPort)
	if l > 0 {
		n += 1 + l + sovConf(uint64(l))
	}
	l = len(m.DohUrl)
	if l > 0 {
		n += 1 + l + sovConf(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovConf(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConf(x uint64) (n int) {
	return sovConf(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Config) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConf
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Config: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Config: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Servers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConf
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Servers = append(m.Servers, Server{})
			if err := m.Servers[len(m.Servers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResolveMode", wireType)
			}
			m.ResolveMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResolveMode |= Config_ResolveMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListenAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConf
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ListenAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogQueries", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LogQueries = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipConf(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthConf
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthConf
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Server) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConf
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Server: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Server: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConf
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= Server_Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HostPort", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConf
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HostPort = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DohUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthConf
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthConf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DohUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConf(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthConf
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthConf
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConf(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConf
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConf
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConf
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConf
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConf
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConf
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConf        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConf          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConf = fmt.Errorf("proto: unexpected end of group")
)
